#CI项目名
name: 编译Lede_hiwifi_c526a

on:
  #自动编译：每天早上4点
  #schedule:
    #- cron: 0 20 * * *
  #手动编译
  workflow_dispatch:

  workflow_call:
    inputs:
      WRT_BRANCH:
        required: true
        type: string
      WRT_TARGET:
        required: true
        type: string
      WRT_THEME:
        required: true
        type: string
      WRT_NAME:
        required: true
        type: string
      WRT_WIFI:
        required: true
        type: string
      WRT_URL:
        required: true
        type: string
      WRT_IP:
        required: true
        type: string
      WRT_PW:
        required: true
        type: string
      WRT_CFG:
        required: false
        default: 'false'
        type: string

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  WRT_BRANCH: ${{inputs.WRT_BRANCH}}
  WRT_TARGET: ${{inputs.WRT_TARGET}}
  WRT_THEME: ${{inputs.WRT_THEME}}
  WRT_NAME: ${{inputs.WRT_NAME}}
  WRT_WIFI: ${{inputs.WRT_WIFI}}
  WRT_URL: ${{inputs.WRT_URL}}
  WRT_IP: ${{inputs.WRT_IP}}
  WRT_PW: ${{inputs.WRT_PW}}
  WRT_CFG: ${{inputs.WRT_CFG}}

#CI权限
permissions: write-all

#CI任务
jobs:
  wrt_config:
    #调用公用编译核心WRT-CORE.yml
    #uses: ./.github/workflows/WRT-CORE.yml
    with:
      #编译平台，ipq40xx
      WRT_TARGET: ipq40xx
      #默认主题
      WRT_THEME: opentopd
      #默认主机名
      WRT_NAME: OpenWRT
      #默认WIFI名
      WRT_WIFI: OpenWRT
      #默认密码，仅作提示，修改无用
      WRT_PW: password
      #默认地址
      WRT_IP: 192.168.168.1
      #默认源码
      WRT_URL: https://github.com/coolsnowwolf/lede.git
      #默认分支
      WRT_BRANCH: master

 
